from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path("", views.home, name="home"),
    path("map/", views.map, name="map"),
    path("ahmadnagardata", views.ahmadnagar, name="ahmadnagardata"),
    path("akoladata", views.akola, name="akoladata"),
    path("amravatidata", views.amravati, name="amravatidata"),
    path("aurangabaddata", views.aurangabad, name="aurangabaddata"),
    path("beeddata", views.beed, name="beeddata"),
    path("bhandaradata", views.bhandara, name="bhandaradata"),
    path("buldanadata", views.buldana, name="buldanadata"),
    path("chandrapurdata", views.chandrapur, name="chandrapurdata"),
    path("dhuledata", views.dhule, name="dhuledata"),
    path("gadchirolidata", views.gadchiroli, name="gadchirolidata"),
    path("hingolidata", views.hingoli, name="hingolidata"),
    path("jalgaondata", views.jalgaon, name="jalgaondata"),
    path("jalnadata", views.jalna, name="jalnadata"),
    path("kolhapurdata", views.kolhapur, name="kolhapurdata"),
    path("laturdata", views.latur, name="laturdata"),
    path("mumbaidata", views.mumbai, name="mumbaidata"),
    path("nagpurdata", views.nagpur, name="nagpurdata"),
    path("nandeddata", views.nanded, name="nandeddata"),
    path("nandurbardata", views.nandurbar, name="nandurbardata"),
    path("nashikdata", views.nashik, name="nashikdata"),
    path("osmanabaddata", views.osmanabad, name="osmanabaddata"),
    path("parbhanidata", views.parbhani, name="parbhanidata"),
    path("punedata", views.pune, name="punedata"),
    path("raigaddata", views.raigad, name="raigaddata"),
    path("ratnagiridata", views.ratnagiri, name="ratnagiridata"),
    path("sanglidata", views.sangli, name="sanglidata"),
    path("sataradata", views.satara, name="sataradata"),
    path("sindhudurgdata", views.sindhudurg, name="sindhudurgdata"),
    path("solapurdata", views.solapur, name="solapurdata"),
    path("thanedata", views.thane, name="thanedata"),
    path("wardhadata", views.wardha, name="wardhadata"),
    path("washimdata", views.washim, name="washimdata"),
    path("yavatmaldata", views.yavatmal, name="yavatmaldata"),
]
