# Generated by Django 3.1.2 on 2021-03-07 20:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('school_nam', models.CharField(blank=True, max_length=100, null=True)),
                ('schcd', models.BigIntegerField(blank=True, null=True)),
                ('schcat', models.CharField(blank=True, max_length=23, null=True)),
                ('schmgt', models.CharField(blank=True, max_length=33, null=True)),
                ('estdyear', models.IntegerField(blank=True, null=True)),
                ('distname', models.CharField(blank=True, max_length=24, null=True)),
                ('block_name', models.CharField(blank=True, max_length=34, null=True)),
                ('village_na', models.CharField(blank=True, max_length=34, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('bldstatus', models.CharField(blank=True, max_length=9, null=True)),
                ('clrooms', models.IntegerField(blank=True, null=True)),
                ('toiletb', models.IntegerField(blank=True, null=True)),
                ('toilet_g', models.IntegerField(blank=True, null=True)),
                ('mealsinsch', models.IntegerField(blank=True, null=True)),
                ('library_yn', models.IntegerField(blank=True, null=True)),
                ('pground_yn', models.IntegerField(blank=True, null=True)),
                ('water', models.IntegerField(blank=True, null=True)),
                ('medchk_yn', models.IntegerField(blank=True, null=True)),
                ('computer', models.IntegerField(blank=True, null=True)),
                ('field_22', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='map',
        ),
    ]
